{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "705cbbb9-eb04-4ef7-b793-0322e9cf0481",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-06-23 23:31:27.337 No runtime found, using MemoryCacheStorageManager\n",
      "2026-06-23 23:31:27.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.399 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.404 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.477 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.485 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.489 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.491 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.495 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-23 23:31:27.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import re\n",
    "import nltk\n",
    "from nltk.corpus import stopwords\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import classification_report, accuracy_score\n",
    "from transformers import pipeline\n",
    "import requests\n",
    "import os\n",
    "import streamlit as st\n",
    "import spacy\n",
    "\n",
    "# -----------------------------\n",
    "# Cache the Hugging Face model\n",
    "# -----------------------------\n",
    "@st.cache_resource\n",
    "def load_nli_model():\n",
    "    return pipeline(\"text-classification\", model=\"roberta-large-mnli\", return_all_scores=True)\n",
    "\n",
    "nli_model = load_nli_model()\n",
    "_ = nli_model(\"Warmup headline\", text_pair=\"Warmup trusted article\")  # warm-up\n",
    "\n",
    "# -----------------------------\n",
    "# -----------------------------\n",
    "# Load spaCy for entity extraction (with fallback)\n",
    "# -----------------------------\n",
    "import subprocess, sys\n",
    "\n",
    "def get_spacy_model():\n",
    "    try:\n",
    "        return spacy.load(\"en_core_web_sm\")\n",
    "    except OSError:\n",
    "        subprocess.run([sys.executable, \"-m\", \"spacy\", \"download\", \"en_core_web_sm\"])\n",
    "        return spacy.load(\"en_core_web_sm\")\n",
    "\n",
    "nlp = get_spacy_model()\n",
    "\n",
    "# -----------------------------\n",
    "# Cache trusted articles\n",
    "# -----------------------------\n",
    "@st.cache_data\n",
    "def fetch_trusted_news(use_cache=True):\n",
    "    cache_file = \"trusted_news.csv\"\n",
    "    if use_cache and os.path.exists(cache_file):\n",
    "        df = pd.read_csv(cache_file)\n",
    "        return df['article'].tolist()\n",
    "\n",
    "    API_KEY = \"ea359e7ffa4249798fcf2dd2a5f4ec5e\"\n",
    "    url = f\"https://newsapi.org/v2/top-headlines?country=us&apiKey={API_KEY}\"\n",
    "    response = requests.get(url)\n",
    "    data = response.json()\n",
    "\n",
    "    trusted_articles = []\n",
    "    for article in data.get('articles', []):\n",
    "        text = (article.get('title') or \"\") + \" \" + (article.get('description') or \"\")\n",
    "        trusted_articles.append(text)\n",
    "\n",
    "    pd.DataFrame(trusted_articles, columns=['article']).to_csv(cache_file, index=False)\n",
    "    return trusted_articles\n",
    "\n",
    "# -----------------------------\n",
    "# Exact similarity checking\n",
    "# -----------------------------\n",
    "def check_exact_match(input_news, trusted_articles):\n",
    "    for trusted in trusted_articles:\n",
    "        if input_news.strip().lower() == trusted.strip().lower():\n",
    "            return True\n",
    "    return False\n",
    "\n",
    "# -----------------------------\n",
    "# Entity & event extraction\n",
    "# -----------------------------\n",
    "def extract_entities_events(text: str) -> dict:\n",
    "    doc = nlp(text)\n",
    "    entities = {\"PERSON\": set(), \"ORG\": set(), \"GPE\": set()}\n",
    "    for ent in doc.ents:\n",
    "        if ent.label_ in entities:\n",
    "            entities[ent.label_].add(ent.text)\n",
    "\n",
    "    lower = text.lower()\n",
    "    events = {\n",
    "        \"death\": any(k in lower for k in [\"died\", \"death\", \"passed away\", \"last rite\", \"funeral\"]),\n",
    "        \"appearance\": any(k in lower for k in [\"appearance\", \"spotted\", \"photo\", \"picture\", \"video\", \"interview\", \"birthday\"]),\n",
    "        \"attack\": any(k in lower for k in [\"attack\", \"missile\", \"strike\", \"war\", \"bomb\", \"drone\"]),\n",
    "        \"absurd_duration\": bool(re.search(r\"\\b\\d{4,}\\s+years?\\b\", lower)),\n",
    "    }\n",
    "    return {\"entities\": {k: list(v) for k, v in entities.items()}, \"events\": events}\n",
    "\n",
    "# -----------------------------\n",
    "# Build entity state from trusted sources\n",
    "# -----------------------------\n",
    "def build_entity_state(trusted_articles: list) -> dict:\n",
    "    state = {}\n",
    "    for art in trusted_articles:\n",
    "        info = extract_entities_events(art)\n",
    "        persons = info[\"entities\"].get(\"PERSON\", [])\n",
    "        has_appearance = info[\"events\"][\"appearance\"]\n",
    "\n",
    "        for p in persons:\n",
    "            if p not in state:\n",
    "                state[p] = {\"alive_recent\": False, \"evidence\": []}\n",
    "            if has_appearance:\n",
    "                state[p][\"alive_recent\"] = True\n",
    "            state[p][\"evidence\"].append(art)\n",
    "    return state\n",
    "\n",
    "# -----------------------------\n",
    "# Logical contradiction checks\n",
    "# -----------------------------\n",
    "def detect_logical_contradiction(input_text: str, entity_state: dict) -> tuple:\n",
    "    info = extract_entities_events(input_text)\n",
    "    persons = info[\"entities\"].get(\"PERSON\", [])\n",
    "    events = info[\"events\"]\n",
    "\n",
    "    if events[\"absurd_duration\"]:\n",
    "        return True, \"🔴 Fake: Impossible duration detected\"\n",
    "\n",
    "    if events[\"death\"] and persons:\n",
    "        for p in persons:\n",
    "            st = entity_state.get(p)\n",
    "            if st and st.get(\"alive_recent\"):\n",
    "                return True, f\"🔴 Fake: Logical contradiction — {p} reported alive recently vs death claim\"\n",
    "\n",
    "    return False, \"\"\n",
    "\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "tfidf = TfidfVectorizer(stop_words=\"english\")\n",
    "\n",
    "def semantic_similarity(a, b):\n",
    "    vecs = tfidf.fit_transform([a, b])\n",
    "    return cosine_similarity(vecs[0], vecs[1])[0][0]\n",
    "\n",
    "\n",
    "\n",
    "# ----------------------------------\n",
    "# Relevence checking\n",
    "def is_relevant(input_text, trusted_text):\n",
    "    # Entity overlap\n",
    "    input_ents = extract_entities_events(input_text)[\"entities\"]\n",
    "    trusted_ents = extract_entities_events(trusted_text)[\"entities\"]\n",
    "\n",
    "    for key in input_ents:\n",
    "        if set(input_ents[key]) & set(trusted_ents[key]):\n",
    "            return True\n",
    "\n",
    "    # Semantic similarity fallback\n",
    "    sim = semantic_similarity(input_text, trusted_text)\n",
    "    return sim > 0.25   # this threshold works well for headlines\n",
    "\n",
    "\n",
    "\n",
    "#-----------------------------------\n",
    "# -----------------------------\n",
    "# NLI comparison (confidence)\n",
    "# -----------------------------\n",
    "def nli_confidence_verdict(input_text: str, trusted_articles: list, top_n: int = 3, min_sim: float = 0.25):\n",
    "    max_similarity = 0.0\n",
    "    contradiction_score = 0.0\n",
    "    results = []\n",
    "    \n",
    "    for trusted in trusted_articles[:20]:\n",
    "        # Semantic similarity\n",
    "        sim = semantic_similarity(input_text, trusted)\n",
    "        max_similarity = max(max_similarity, sim)\n",
    "\n",
    "        # NLI for contradiction only\n",
    "        result = nli_model(input_text, text_pair=trusted)\n",
    "        scores = result[0]\n",
    "\n",
    "        contra = max(\n",
    "            (s for s in scores if \"contra\" in s['label'].lower()),\n",
    "            key=lambda x: x['score']\n",
    "        )\n",
    "\n",
    "        if contra['score'] > 0.8:\n",
    "            contradiction_score = max(contradiction_score, contra['score'])\n",
    "\n",
    "        results.append((trusted, sim, contra['score']))\n",
    "        \n",
    "    # Sort by similarity\n",
    "    results.sort(key=lambda x: x[1], reverse=True)\n",
    "    top_matches = [r for r in results if r[1] >= min_sim][:top_n]\n",
    "    \n",
    "    if contradiction_score > 0:\n",
    "        verdict = f\"🔴 Probably Fake: {int(contradiction_score*100)}% confidence\"\n",
    "        top_matches = [r for r in results if r[2] > 0.5][:top_n]\n",
    "    elif max_similarity > 0.30:\n",
    "        verdict = f\"🟢 Likely Real: matched trusted reporting ({int(max_similarity*100)}% similarity)\"\n",
    "        top_matches = [r for r in results if r[1] >= min_sim][:top_n]\n",
    "    else:\n",
    "        verdict = \"🟡 Needs Review (no supporting trusted news)\"\n",
    "        top_matches = []\n",
    "        \n",
    "    return verdict, top_matches\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# Combined system (Hybrid)\n",
    "# -----------------------------\n",
    "def full_check(news_text):\n",
    "    trusted_articles = fetch_trusted_news(use_cache=True)\n",
    "\n",
    "    # Exact match check\n",
    "    if check_exact_match(news_text, trusted_articles):\n",
    "        return {\n",
    "            #\"Classification\": \"Real News\",\n",
    "            \"ContradictionCheck\": \"🟢 Likely Real : Exact match found in trusted dataset (100% similarity)\"\n",
    "        }\n",
    "\n",
    "    # Build entity state\n",
    "    entity_state = build_entity_state(trusted_articles)\n",
    "\n",
    "    # Logical contradiction check\n",
    "    is_contra, reason = detect_logical_contradiction(news_text, entity_state)\n",
    "    if is_contra:\n",
    "        return {\"ContradictionCheck_3\": reason, \"Matches\": []} \n",
    "\n",
    "    # NLI fallback\n",
    "    verdict, matches = nli_confidence_verdict(news_text, trusted_articles)\n",
    "    return {\"ContradictionCheck_3\": verdict, \"Matches\": matches}\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "# -------------------------------\n",
    "# Streamlit UI\n",
    "# -----------------------------\n",
    "#import streamlit as st\n",
    "\n",
    "# Page setup\n",
    "st.set_page_config(\n",
    "    page_title=\"Fake News Detection\",\n",
    "    page_icon=\"📰\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# Centered heading\n",
    "st.markdown(\"<h1 style='text-align: center; color: #2E86C1;'>📰 Fake News Detection Demo</h1>\", unsafe_allow_html=True)\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# Create two columns\n",
    "col1, col2 = st.columns([1, 1])  # equal width, you can adjust ratio like [1,2]\n",
    "\n",
    "# Left column: input\n",
    "with col1:\n",
    "    user_input = st.text_area(\"Enter a news headline or article:\")\n",
    "    check_button = st.button(\"Check\")\n",
    "\n",
    "# Right column: results\n",
    "with col2:\n",
    "    if check_button:\n",
    "        if not user_input.strip():\n",
    "            st.warning(\"Please enter some text.\")\n",
    "        else:\n",
    "            text = user_input.strip().lower()\n",
    "        \n",
    "            # Hard-coded demo outputs\n",
    "            if text == \"modi died yesterday\":\n",
    "                verdict_text = \"🔴 Fake: Hardcoded demo result\"\n",
    "            elif text == \"lionel messi scored a goal\":\n",
    "                verdict_text = \"🟢 Real: Hardcoded demo result\"\n",
    "            elif text == \"the weather is nice\":\n",
    "                verdict_text = \"🟡 Neutral: Hardcoded demo result\"\n",
    "            else:\n",
    "                verdict_text = \"🟡 Needs Review (demo fallback)\"\n",
    "        \n",
    "            # Verdict display with color-coded boxes\n",
    "            if \"Real\" in verdict_text:\n",
    "                st.success(verdict_text)\n",
    "            elif \"Fake\" in verdict_text:\n",
    "                st.error(verdict_text)\n",
    "            else:\n",
    "                st.warning(verdict_text)\n",
    "\n",
    "            # Related matches section (disabled for demo)\n",
    "            st.info(\"Demo mode: matches not shown.\")\n",
    "\n",
    "# Sidebar cache control\n",
    "with st.sidebar:\n",
    "    if st.button(\"Clear Cache\"):\n",
    "        st.cache_data.clear()\n",
    "        st.cache_resource.clear()\n",
    "        st.success(\"✅ Cache cleared! Please rerun the app.\")\n",
    "# Footer\n",
    "st.markdown(\"<hr>\", unsafe_allow_html=True)\n",
    "#st.markdown(\"<p style='text-align:center; color:grey;'>Built with ❤️ using Streamlit</p>\", unsafe_allow_html=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b92a8e9a-351d-4157-8851-818babff3cf1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
